### ISSUE TITLE
architect does not run any workflow

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/certificatetpr#12]
I noticed that the tests are not executable because of dependencies not being vendored. I wondered why the circle builds pass though. Turned out architect does not build/test the project at all. 

<img width="1337" alt="screen shot 2017-05-04 at 11 50 27" src="https://cloud.githubusercontent.com/assets/552769/25698653/f3947538-30bf-11e7-9be0-cafa441dd60a.png">

See https://circleci.com/gh/giantswarm/certificatetpr/15. 

FYI @JosephSalisbury @rossf7 @asymmetric

**Comment by rossf7** [comment]
The workflow in architect is looking for a main.go.

See https://github.com/giantswarm/certificatetpr/pull/2#issuecomment-289016712

**Comment by JosephSalisbury** [comment]
See https://github.com/giantswarm/architect/issues/46
