### ISSUE TITLE
Decide whether to use api or apiserver as the cluster component for API certs

### ISSUE THREAD

**Issue by rossf7** [giantswarm/certificatetpr#4]
Decide based on community conventions in tools like kubeadm and kops.

**Comment by asymmetric** [comment]
Kops seems to use "apiserver" [much more often](https://github.com/kubernetes/kops/search?utf8=%E2%9C%93&q=apiserver&type=) than [api-server](https://github.com/kubernetes/kops/search?utf8=%E2%9C%93&q=api-server&type=).

**Comment by xh3b4sd** [comment]
Is this still relevant? AFAIK we are using the term `api` for subdomains in the cert common name and for the component names.

**Comment by rossf7** [comment]
Closing as we went with `api` because the cluster components then match the domains in the cluster TPO.
